USE Natalie;
GO

IF EXISTS (
    SELECT 1 
    FROM sys.tables 
    WHERE [name] = 'TabA'
)

BEGIN
    ALTER TABLE dbo.TabA
    -- DROP CONSTRAINT UNIQUE_KEY_TabA_RC --UNIQUE (RC);
    ADD CONSTRAINT UNIQUE_KEY_TabA_RC UNIQUE (RC);
END
